# Generated by Django 3.2 on 2021-04-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_id', models.CharField(max_length=15)),
                ('ranking', models.CharField(max_length=15)),
                ('player_img', models.URLField()),
                ('name', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=40)),
                ('age', models.CharField(max_length=10)),
                ('nation_img', models.URLField()),
                ('nation_title', models.CharField(max_length=25)),
                ('team_img', models.URLField()),
                ('team_title', models.CharField(max_length=25)),
                ('player_value', models.CharField(max_length=15)),
            ],
        ),
    ]
