# Generated by Django 3.2 on 2021-05-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_id', models.IntegerField()),
                ('ranking', models.IntegerField()),
                ('club_image', models.URLField()),
                ('name', models.CharField(max_length=225)),
                ('Competition_image', models.URLField()),
                ('Competition', models.CharField(max_length=255)),
                ('club_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_id', models.IntegerField()),
                ('ranking', models.IntegerField()),
                ('player_image', models.URLField()),
                ('name', models.CharField(max_length=225)),
                ('position', models.CharField(max_length=225)),
                ('age', models.CharField(max_length=10)),
                ('nation_image', models.URLField()),
                ('nation', models.CharField(max_length=225)),
                ('team_image', models.URLField()),
                ('team', models.CharField(max_length=225)),
                ('value', models.CharField(max_length=225)),
            ],
        ),
    ]
