# Generated by Django 3.2 on 2021-05-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_id', models.CharField(max_length=225)),
                ('League', models.CharField(max_length=225)),
                ('ranking', models.CharField(default='', max_length=225)),
                ('state', models.CharField(default='', max_length=225)),
                ('name', models.CharField(max_length=225)),
                ('play', models.CharField(max_length=225)),
                ('win', models.CharField(max_length=225)),
                ('draw', models.CharField(max_length=225)),
                ('lose', models.CharField(max_length=225)),
                ('gf', models.CharField(max_length=225)),
                ('gd', models.CharField(max_length=225)),
                ('ga', models.CharField(max_length=225)),
                ('pts', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='ClubValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_id', models.IntegerField()),
                ('ranking', models.IntegerField()),
                ('club_image', models.URLField()),
                ('name', models.CharField(max_length=225)),
                ('Competition', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_id', models.IntegerField()),
                ('League', models.CharField(max_length=225)),
                ('name', models.CharField(max_length=225)),
                ('age', models.CharField(max_length=225)),
                ('position', models.CharField(max_length=225)),
                ('Games', models.CharField(max_length=225)),
                ('Goals', models.CharField(max_length=225)),
                ('Assists', models.CharField(max_length=225)),
                ('SpG', models.CharField(max_length=225)),
                ('PS', models.CharField(max_length=225)),
                ('MotM', models.CharField(max_length=225)),
                ('Rating', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_id', models.IntegerField()),
                ('_position', models.CharField(max_length=225)),
                ('ranking', models.IntegerField()),
                ('player_image', models.URLField()),
                ('name', models.CharField(max_length=225)),
                ('position', models.CharField(max_length=225)),
                ('age', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=225)),
            ],
        ),
    ]
