# Generated by Django 3.2 on 2021-04-22 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerdata',
            old_name='nation_title',
            new_name='nation',
        ),
        migrations.RenameField(
            model_name='playerdata',
            old_name='nation_img',
            new_name='nation_image',
        ),
        migrations.RenameField(
            model_name='playerdata',
            old_name='player_img',
            new_name='player_image',
        ),
        migrations.RenameField(
            model_name='playerdata',
            old_name='team_title',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='playerdata',
            old_name='team_img',
            new_name='team_image',
        ),
        migrations.RenameField(
            model_name='playerdata',
            old_name='player_value',
            new_name='value',
        ),
    ]
