# Generated by Django 3.2 on 2021-05-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundesligaPlayerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_id', models.CharField(max_length=225)),
                ('name', models.CharField(max_length=225)),
                ('age', models.CharField(max_length=225)),
                ('position', models.CharField(max_length=225)),
                ('Games', models.CharField(max_length=225)),
                ('Goals', models.CharField(max_length=225)),
                ('Assists', models.CharField(max_length=225)),
                ('SpG', models.CharField(max_length=225)),
                ('PS', models.CharField(max_length=225)),
                ('MotM', models.CharField(max_length=225)),
                ('Rating', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='LaligaPlayerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_id', models.CharField(max_length=225)),
                ('name', models.CharField(max_length=225)),
                ('age', models.CharField(max_length=225)),
                ('position', models.CharField(max_length=225)),
                ('Games', models.CharField(max_length=225)),
                ('Goals', models.CharField(max_length=225)),
                ('Assists', models.CharField(max_length=225)),
                ('SpG', models.CharField(max_length=225)),
                ('PS', models.CharField(max_length=225)),
                ('MotM', models.CharField(max_length=225)),
                ('Rating', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Ligue1PlayerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_id', models.CharField(max_length=225)),
                ('name', models.CharField(max_length=225)),
                ('age', models.CharField(max_length=225)),
                ('position', models.CharField(max_length=225)),
                ('Games', models.CharField(max_length=225)),
                ('Goals', models.CharField(max_length=225)),
                ('Assists', models.CharField(max_length=225)),
                ('SpG', models.CharField(max_length=225)),
                ('PS', models.CharField(max_length=225)),
                ('MotM', models.CharField(max_length=225)),
                ('Rating', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='PremierPlayerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_id', models.CharField(max_length=225)),
                ('name', models.CharField(max_length=225)),
                ('age', models.CharField(max_length=225)),
                ('position', models.CharField(max_length=225)),
                ('Games', models.CharField(max_length=225)),
                ('Goals', models.CharField(max_length=225)),
                ('Assists', models.CharField(max_length=225)),
                ('SpG', models.CharField(max_length=225)),
                ('PS', models.CharField(max_length=225)),
                ('MotM', models.CharField(max_length=225)),
                ('Rating', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='SerieAPlayerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_id', models.CharField(max_length=225)),
                ('name', models.CharField(max_length=225)),
                ('age', models.CharField(max_length=225)),
                ('position', models.CharField(max_length=225)),
                ('Games', models.CharField(max_length=225)),
                ('Goals', models.CharField(max_length=225)),
                ('Assists', models.CharField(max_length=225)),
                ('SpG', models.CharField(max_length=225)),
                ('PS', models.CharField(max_length=225)),
                ('MotM', models.CharField(max_length=225)),
                ('Rating', models.CharField(max_length=225)),
            ],
        ),
    ]
