# Generated by Django 3.2 on 2021-04-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_data', '0002_auto_20210422_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.CharField(max_length=15)),
                ('club_image', models.URLField()),
                ('name', models.CharField(max_length=15)),
                ('Competition_image', models.URLField()),
                ('Competition', models.CharField(max_length=25)),
                ('club_value', models.CharField(max_length=15)),
            ],
        ),
    ]
