# Generated by Django 3.2 on 2021-05-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_data', '0002_bundesligaplayerstatistics_laligaplayerstatistics_ligue1playerstatistics_premierplayerstatistics_ser'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundesligaClubStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_id', models.IntegerField()),
                ('name', models.CharField(max_length=225)),
                ('play', models.CharField(max_length=225)),
                ('win', models.CharField(max_length=225)),
                ('draw', models.CharField(max_length=225)),
                ('lose', models.CharField(max_length=225)),
                ('gf', models.CharField(max_length=225)),
                ('gd', models.CharField(max_length=225)),
                ('ga', models.CharField(max_length=225)),
                ('pts', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='LaligaClubStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_id', models.IntegerField()),
                ('name', models.CharField(max_length=225)),
                ('play', models.CharField(max_length=225)),
                ('win', models.CharField(max_length=225)),
                ('draw', models.CharField(max_length=225)),
                ('lose', models.CharField(max_length=225)),
                ('gf', models.CharField(max_length=225)),
                ('gd', models.CharField(max_length=225)),
                ('ga', models.CharField(max_length=225)),
                ('pts', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Ligue1ClubStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_id', models.IntegerField()),
                ('name', models.CharField(max_length=225)),
                ('play', models.CharField(max_length=225)),
                ('win', models.CharField(max_length=225)),
                ('draw', models.CharField(max_length=225)),
                ('lose', models.CharField(max_length=225)),
                ('gf', models.CharField(max_length=225)),
                ('gd', models.CharField(max_length=225)),
                ('ga', models.CharField(max_length=225)),
                ('pts', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='PremierClubStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_id', models.IntegerField()),
                ('name', models.CharField(max_length=225)),
                ('play', models.CharField(max_length=225)),
                ('win', models.CharField(max_length=225)),
                ('draw', models.CharField(max_length=225)),
                ('lose', models.CharField(max_length=225)),
                ('gf', models.CharField(max_length=225)),
                ('gd', models.CharField(max_length=225)),
                ('ga', models.CharField(max_length=225)),
                ('pts', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='SerieAClubStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_id', models.IntegerField()),
                ('name', models.CharField(max_length=225)),
                ('play', models.CharField(max_length=225)),
                ('win', models.CharField(max_length=225)),
                ('draw', models.CharField(max_length=225)),
                ('lose', models.CharField(max_length=225)),
                ('gf', models.CharField(max_length=225)),
                ('gd', models.CharField(max_length=225)),
                ('ga', models.CharField(max_length=225)),
                ('pts', models.CharField(max_length=225)),
            ],
        ),
        migrations.AlterField(
            model_name='bundesligaplayerstatistics',
            name='specific_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='laligaplayerstatistics',
            name='specific_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ligue1playerstatistics',
            name='specific_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='premierplayerstatistics',
            name='specific_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='serieaplayerstatistics',
            name='specific_id',
            field=models.IntegerField(),
        ),
    ]
