# Generated by Django 3.2 on 2021-05-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_data', '0003_auto_20210506_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundesligaclubstatistics',
            name='ranking',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AddField(
            model_name='bundesligaclubstatistics',
            name='state',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AddField(
            model_name='laligaclubstatistics',
            name='ranking',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AddField(
            model_name='laligaclubstatistics',
            name='state',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AddField(
            model_name='ligue1clubstatistics',
            name='ranking',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AddField(
            model_name='ligue1clubstatistics',
            name='state',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AddField(
            model_name='premierclubstatistics',
            name='ranking',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AddField(
            model_name='premierclubstatistics',
            name='state',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AddField(
            model_name='serieaclubstatistics',
            name='ranking',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AddField(
            model_name='serieaclubstatistics',
            name='state',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='bundesligaclubstatistics',
            name='specific_id',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='laligaclubstatistics',
            name='specific_id',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='ligue1clubstatistics',
            name='specific_id',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='premierclubstatistics',
            name='specific_id',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='serieaclubstatistics',
            name='specific_id',
            field=models.CharField(max_length=225),
        ),
    ]
