# Generated by Django 3.2 on 2021-04-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_data', '0003_clubdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubdata',
            name='specific_id',
            field=models.CharField(default='', max_length=15),
        ),
    ]
